### ISSUE TITLE
Shared sources in config TOML

### ISSUE THREAD

**Issue by Yiling-J** [Yiling-J/tablepilot#14]
Enable the ability to define shared sources in the configuration TOML file, allowing users to reuse them in the schema JSON for improved maintainability and consistency.
```toml
[[sources]]
name = "countries"
type = "list"
options = ["USA", "Canada", "Germany", "France", "Japan"]

[[sources]]
name = "payment_methods"
type = "list"
options = ["Credit Card", "PayPal", "Bank Transfer", "Cryptocurrency"]
```
